程式碼整理和增加點讚功能
AhernShaia/Tech-Tonic pull request #30
Opened 2023-04-29 09:07 UTC by weihsiang120

<img width="228" alt="螢幕擷取畫面 2023-04-29 170430" src="https://user-images.githubusercontent.com/127068922/235294587-caf463bb-94d7-4b27-ba1b-df5fef9a79ca.png">
點即可以按讚，按過的可以取消，並且會顯示按讚數量

rubocop程式碼整理

2023-04-29 09:13 UTC, shiangogo commented on config/routes.rb
>    root to: 'home#index'
這行會動嗎？

2023-04-30 04:14 UTC, AhernShaia requested changes
把程式碼說明清楚再推，為什麽有大量的檔案變更(修改單引號跟雙引號，增加兩個空格...等等)，用什麼套件？

2023-04-30 04:31 UTC, weihsiang120 commented
> 把程式碼說明清楚再推，為什麽有大量的檔案變更(修改單引號跟雙引號，增加兩個空格...等等)，用什麼套件？

大部分是rubocop的修正，包含單雙引號和空格

2023-04-30 04:33 UTC, weihsiang120 commented
另外有修正的是搜尋欄的icon改成button，和增加點讚功能，登入的使用者才可以點讚

2023-04-30 04:45 UTC, weihsiang120 commented
修正搜尋欄是在_navbar.html.erb，如下
<img width="714" alt="螢幕擷取畫面 2023-04-30 123743" src="https://user-images.githubusercontent.com/127068922/235335905-802e5ff0-8b61-43cd-97dc-6b550cf9216b.png">

而增加的_like.html.erb則是點讚功能，並且在_post.html.erb render 出來，如下
<img width="337" alt="螢幕擷取畫面 2023-04-30 124224" src="https://user-images.githubusercontent.com/127068922/235335917-16cd6f96-d2bb-48d3-8b84-2f25fff37538.png">
在路徑給一個like
<img width="660" alt="螢幕擷取畫面 2023-04-30 124231" src="https://user-images.githubusercontent.com/127068922/235335924-bd287138-8174-435c-a125-5f5dc75285f6.png">
把like寫在一_like.html.erb
<img width="424" alt="螢幕擷取畫面 2023-04-30 124153" src="https://user-images.githubusercontent.com/127068922/235335951-0b9d5e9e-e3c1-4721-9594-6e775564df18.png">在_post.html.erb render出來

2023-04-30 04:48 UTC, weihsiang120 commented
另外新加的_like.js.erb目的是讓like狀態和數量能在按下時及時改變並渲染出來

2023-05-02 06:56 UTC, closed without merging